POST https://shopee.vn/api/v4/banner/batch_list_by_spaces

{
    "extra_data": "{}",
			"spaces": [
				{
					"space_key": "PC-VN-CATEGORY_CAROUSEL_01",
					"space_filter": [{ "key": "category_id", "value": "11035639" }],
				},
			],
}

###
GET https://shopee-black.vercel.app/api/v4/recommend/recommend?bundle=daily_discover_main&item_card=3&limit=60&offset=0