POST https://shopee.vn/api/v4/banner/batch_list_by_spaces

{
    "extra_data": "{}",
			"spaces": [
				{
					"space_key": "PC-VN-CATEGORY_CAROUSEL_01",
					"space_filter": [{ "key": "category_id", "value": "11035639" }],
				},
			],
}


### 
GET http://localhost:3000/api/v4/search/search_items?by=pop&categoryids=100578%2C341412&limit=60&match_id=11036132&newest=0&order=desc&page_type=search&scenario=PAGE_CATEGORY&version=2
af-ac-enc-dat: null